export { default as OurTeam } from './ourteam.png'
export { default as Feature } from './features.png'
export {default as LaunchpadImg} from './launchpad-illustration.png'
export {default as MetaverseImg} from './metaverse-illustration.png'
export {default as StakingImg} from './staking-illustration.png'
export {default as TeamPhoto} from './teamphoto.png'
export {default as FooterLogo} from './footerlogo.png'
export { default as FooterIcon} from './footericon.png'
export { default as GalaxyImg } from './galaxy.png'
export { default as GalaxyImg2} from './galaxy2.png'
export { default as backgroundNFT } from './background-detail.png'
export { default as backgroundNFT2 } from './background-detail-2.png'
export { default as ProfileVictor} from './team-1.png'
export { default as ProfileUdin} from './team-2.png'
export { default as ProfileResha} from './team-3.png'
export { default as ProfileAgung} from './team-4.png'
export { default as ProfileFebi} from './team-5.png'
export { default as ProfileRosidi} from './team-6.png'
export { default as ProfileDirga} from './team-7.png'
export { default as StakingNftLogo} from './staking-nft-logo.png'
